name: Deploy Admin to Docker Hub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  admin-build:
    uses: ./.github/workflows/main-deploy-v1.yml
    name: "Build and Deploy for Admin"
    secrets: inherit