name: Deploy Develop Admin to Docker Hub

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  admin-build:
    uses: ./.github/workflows/develop-deploy-v1.yml
    name: "Build and Deploy for Develop Admin"
    secrets: inherit
